### ISSUE TITLE
Consider using website-skeleton of Symfony organization

### ISSUE THREAD

**Issue by mickaelandrieu** [4xxi/skeleton#2]
Hello,

looking (again) at your skeleton, I don't see big differences with the new [website-skeleton](https://github.com/symfony/website-skeleton) released by the Symfony Core team, it's maybe a chance to re-use the official skeleton and enrich it, wdyt?

Mickaël

**Comment by etomilin** [comment]
@mickaelandrieu 
In my opinion website-skeleton has a slightly different purpose. It's main idea is to replace Standard Edition for creating full-featured Symfony framework projects (something that became slightly more complicated for newcomers with Symfony 4 release).
While 4xxi skeleton is somewhere in between the original skeleton and website-skeleton in terms of included symfony dependencies, it also contains a lot of boilerplate configurations for third-party tools and libraries (Docker, Deployer, etc.). They won't make much sense in website-skeleton, because obviously they will bring coupling to the related tools, that is not needed in the official distribution of the framework.

**Comment by mickaelandrieu** [comment]
ok, thanks for  the explanation.

Feel free to close!
